--https://velog.io/@hye_b/ProgrammersMySQL-%EC%9A%B0%EC%9C%A0%EC%99%80-%EC%9A%94%EA%B1%B0%ED%8A%B8%EA%B0%80-%EB%8B%B4%EA%B8%B4-%EC%9E%A5%EB%B0%94%EA%B5%AC%EB%8B%88

SELECT DISTINCT CART_ID FROM CART_PRODUCTS
WHERE NAME = "Milk" AND 
CART_ID IN (SELECT CART_ID FROM CART_PRODUCTS
            WHERE NAME = "Yogurt")
ORDER BY CART_ID
